language: python
python:
    - "3.6"
    - "3.5"
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database coding_test;' -U postgres
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade
script: "python manage.py test --verbosity=2"
sudo: false
notifications:
  email: false