language: perl
perl:
    - "5.24"
    - "5.22"
    - "5.20"
services:
    - postgresql
env:
  global:
    - PERL_CPANM_OPT="--notest --force --skip-satisfied"
    - MOJO_MODE=development
    - MOJO_MIGRATIONS_DEBUG=1
install:
    - "cpanm --installdeps ."
before_script:
    - psql -c 'create database coding_test;' -U postgres
    - "perl bin/run.pl migrate"
script: "perl bin/run.pl test"
sudo: false
notifications:
    email: false

